export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    price: 583,
    reviews: 80,
    ratings: "2.0",
  },
  {
    id: 2,
    name: "Smart Watch",
    price: 647,
    reviews: 564,
    ratings: "3.8",
  },
  {
    id: 3,
    name: "Running Shoes",
    price: 823,
    reviews: 87,
    ratings: "0.3",
  },
  { id: 4, name: "Backpack", price: 819, reviews: 929, ratings: "2.2" },
  {
    id: 5,
    name: "Sunglasses",
    price: 834,
    reviews: 177,
    ratings: "2.5",
  },
  {
    id: 6,
    name: "Mechanical Keyboard",
    price: 621,
    reviews: 190,
    ratings: "4.9",
  },
  {
    id: 7,
    name: "Gaming Mouse",
    price: 290,
    reviews: 172,
    ratings: "3.8",
  },
  {
    id: 8,
    name: "Protein Powder",
    price: 523,
    reviews: 51,
    ratings: "2.9",
  },
  {
    id: 9,
    name: "Water Bottle",
    price: 167,
    reviews: 51,
    ratings: "3.3",
  },
  {
    id: 10,
    name: "Coffee Maker",
    price: 1006,
    reviews: 67,
    ratings: "0.9",
  },
  {
    id: 11,
    name: "Noise Cancelling Headphones",
    price: 1033,
    reviews: 218,
    ratings: "2.6",
  },
];
